PlayDeckRazor/Pages/Games/Gateway.cshtml.cs
using System.Collections;
using System.Text;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.ViewFeatures;
using Microsoft.EntityFrameworkCore;
using NuGet.Protocol;
using PlayDeckRazor.Data;
using PlayDeckRazor.Model;
using System;
using System.IO;
using System.Text;

namespace PlayDeckRazor.Pages.Games;

public class GatewayModel : PageModel
{
    private readonly PlayDeckRazor.Data.PlayDeckRazorContext _context;
    
    [BindProperty(SupportsGet = true)]
    public Game Game { get; set; } = default!;
    
    [BindProperty(SupportsGet = true)]
    public int? DeckID { get; set; }
    
    /// <summary>
    /// 0 = Unplayed, 1 = Complete
    /// </summary>
    [BindProperty]
    public int? PlayStatusChange { get; set; }
    [BindProperty]
    public int? RatingChange { get; set; }
    [BindProperty]
    public int? GameID { get; set; }
    
    [BindProperty]
    public bool ToggleFavourite { get; set; }
    
    [BindProperty]
    public string Fav_Toggle { get; set; }

    /// <summary>
    /// id for game to be deleted, submitted by post from _GameCard delete button
    /// </summary>
    [BindProperty]
    public int? GameDeleteId { get; set; }
    
    public GatewayModel(PlayDeckRazorContext context)
    {
        _context = context;
    }
    
    /// <summary>
    /// Takes an ID of a game and returns all details of that game as JSON
    /// </summary>
    /// <param name="id">ID of Game in database</param>
    /// <returns></returns>
    public async Task<IActionResult> OnGetRetrieveAsync(int? id)
    {
        if (_context.Game == null)
        {
            return new NotFoundResult();
        }
        
        var game =  await _context.Game.FirstOrDefaultAsync(g => g.ID == id);
        if (game == null)
        {
            return new NotFoundResult();
        }
        Game = game;
        return new OkObjectResult(game.ToJson());
    }

    /// <summary>
    /// Saves all changes of the posted game if it exists in the database
    /// Returns HTML of a new Game Card with updated details.
    /// </summary>
    /// <returns>_GameCard HTML</returns>
    public async Task<IActionResult> OnPostEditAsync()
    {
        if (!ModelState.IsValid)
        {
            return new BadRequestResult();
        }

        if (GameExists(Game.ID))
        {
            if (Fav_Toggle.Equals("Favourite"))
            {
                Game.Favourite = true;
            }
            _context.Attach(Game).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!GameExists(Game.ID))
                {
                    return new NotFoundResult();
                }
                else
                {
                    throw;
                }
            }
            IndexModel newPartialModel = new IndexModel(_context);
            ViewDataDictionary newViewData = new ViewDataDictionary(new Microsoft.AspNetCore.Mvc.ModelBinding.EmptyModelMetadataProvider(),
                new Microsoft.AspNetCore.Mvc.ModelBinding.ModelStateDictionary()) { { "IndexModel", newPartialModel } };
            newViewData.Model = newPartialModel;
            newViewData["GameCard"] = Game;
            return new PartialViewResult()
            {
                ViewName = "_GameCard",
                ViewData = newViewData,
            };
        }
        return new BadRequestResult();
    }
    
    /// <summary>
    /// Saves all changes of the posted game if it exists in the database
    /// Returns HTML of a new Game Info Panel with updated details.
    /// </summary>
    /// <returns>_GameInfoPanel HTML</returns>
    public async Task<IActionResult> OnPostEditGameViewAsync()
    {
        if (!ModelState.IsValid)
        {
            return new BadRequestResult();
        }

        if (GameExists(Game.ID))
        {
            if (Fav_Toggle.Equals("Favourite"))
            {
                Game.Favourite = true;
            }
            _context.Attach(Game).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!GameExists(Game.ID))
                {
                    return new NotFoundResult();
                }
                else
                {
                    throw;
                }
            }
            GameViewModel newPartialModel = new GameViewModel(_context);
            ViewDataDictionary newViewData = new ViewDataDictionary(new Microsoft.AspNetCore.Mvc.ModelBinding.EmptyModelMetadataProvider(),
                new Microsoft.AspNetCore.Mvc.ModelBinding.ModelStateDictionary()) { { "GameViewModel", newPartialModel } };
            newViewData.Model = newPartialModel;
            newViewData["GameView"] = Game;
            return new PartialViewResult()
            {
                ViewName = "_GameInfoPanel",
                ViewData = newViewData,
            };
        }
        return new BadRequestResult();
    }

    /// <summary>
    /// Adds posted game to the database
    /// Returns HTML of new Game Card
    /// </summary>
    /// <returns>_GameCard HTML</returns>
    public async Task<IActionResult> OnPostAddAsync()
    {
        if (ModelState.IsValid && !GameExists(Game.ID))
        {
            if (Fav_Toggle.Equals("Favourite"))
            {
                Game.Favourite = true;
            }
            _context.Game.Add(Game);
            await _context.SaveChangesAsync();

            IndexModel newPartialModel = new IndexModel(_context);
            ViewDataDictionary newViewData = new ViewDataDictionary(new Microsoft.AspNetCore.Mvc.ModelBinding.EmptyModelMetadataProvider(),
                new Microsoft.AspNetCore.Mvc.ModelBinding.ModelStateDictionary()) { { "IndexModel", newPartialModel } };
            newViewData.Model = newPartialModel;
            newViewData["GameCard"] = Game;
            return new PartialViewResult()
            {
                ViewName = "_GameCard",
                ViewData = newViewData,
            };
        }
        else
        {
            return new BadRequestResult();
        }
        
    }

    private bool GameExists(int id)
    {
        return (_context.Game?.Any(e => e.ID == id)).GetValueOrDefault();
    }
    
    /// <summary>
    /// Finds game with posted ID and removes it from the database
    /// </summary>
    /// <returns>Posted Game ID</returns>
    public async Task<IActionResult> OnPostDeleteAsync()
    {
        
        if (GameDeleteId != null)
        {
            // Ensure game exists and delete
            var game = await _context.Game.FindAsync(GameDeleteId);
            if (game != null)
            {
                _context.Remove(game);
                await _context.SaveChangesAsync();
                return new OkObjectResult(GameDeleteId);
            }
            
            return new NotFoundResult();
            
        }
        return new BadRequestResult();
    }

    /// <summary>
    /// Finds game by posted Game ID and updates its rating property
    /// Returns HTML of new Game Info Panel
    /// </summary>
    /// <returns>_GameInfoPanel HTML</returns>
    public async Task<IActionResult> OnPostRatingChangeAsync()
    {
        Game = await _context.Game.FindAsync(GameID);
        if (Game == null)
        {
            return new NotFoundResult();
        }
        
        if (RatingChange != null)
        {
            Game.Rating = RatingChange;
        } 
        else
        {
            return new BadRequestResult();
        }
        
        _context.Attach(Game).State = EntityState.Modified;
        
        await _context.SaveChangesAsync();

        GameViewModel newPartialModel = new GameViewModel(_context);
        ViewDataDictionary newViewData = new ViewDataDictionary(new Microsoft.AspNetCore.Mvc.ModelBinding.EmptyModelMetadataProvider(),
            new Microsoft.AspNetCore.Mvc.ModelBinding.ModelStateDictionary()) { { "GameViewModel", newPartialModel } };
        newViewData.Model = newPartialModel;
        newViewData["GameView"] = Game;
        return new PartialViewResult()
        {
            ViewName = "_GameInfoPanel",
            ViewData = newViewData,
        };
    }

    /// <summary>
    /// Finds game by posted Game ID and updates its PlayStatus property
    /// Returns new Game Info Panel HTML
    /// </summary>
    /// <returns>_GameInfoPanel HTML</returns>
    public async Task<IActionResult> OnPostPlayStatusChangeAsync()
    {
        Game = await _context.Game.FindAsync(GameID);
        if (Game == null)
        {
            return new NotFoundResult();
        }
        
        if (PlayStatusChange != null)
        {
            Game.PlayStatus = PlayStatusChange;
        }
        else
        {
            return new BadRequestResult();
        }
        
        _context.Attach(Game).State = EntityState.Modified;
        
        await _context.SaveChangesAsync();

        GameViewModel newPartialModel = new GameViewModel(_context);
        ViewDataDictionary newViewData = new ViewDataDictionary(new Microsoft.AspNetCore.Mvc.ModelBinding.EmptyModelMetadataProvider(),
            new Microsoft.AspNetCore.Mvc.ModelBinding.ModelStateDictionary()) { { "GameViewModel", newPartialModel } };
        newViewData.Model = newPartialModel;
        newViewData["GameView"] = Game;
        return new PartialViewResult()
        {
            ViewName = "_GameInfoPanel",
            ViewData = newViewData,
        };
    }
    
    /// <summary>
    /// Finds game by posted Game ID and updates its Favourite property
    /// Returns new Game Info Panel HTML
    /// </summary>
    /// <returns>_GameInfoPanel HTML</returns>

PlayDeckRazor/Pages/Shared/_ModalGameDetails.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PlayDeckRazor.Model;

namespace PlayDeckRazor.Pages.Shared;

public class _ModalGameDetailsModel : PageModel
{
    public Game Game { get; set; }
    
    /// <summary>
    /// User friendly display of different decks which are otherwise represented as ints
    /// </summary>
    public List<SelectListItem> Decks { get; set; }
    /// <summary>
    /// User friendly display of different PlayStatus which are otherwise represented as ints
    /// </summary>
    public List<SelectListItem> Statuses { get; set; }
    
    public string Fav_Toggle { get; set; }
    
    
    public _ModalGameDetailsModel(PlayDeckRazor.Data.PlayDeckRazorContext context)
    {
        // TODO: Replace with db query when db is updated to store decks
        Decks = new List<SelectListItem>
        {
            new()
            {
                Text = "My Collection",
                Value = "0"
            },
            new()
            {
                Text = "Currently Playing",
                Value = "1"
            },
            new()
            {
                Text = "Complete",
                Value = "2"
            },
            new()
            {
                Text = "Wishlist",
                Value = "3"
            }
        };
            
        Statuses = new List<SelectListItem>
        {
            new()
            {
                Text = "Unfinished",
                Value = "0"
            },
            new()
            {
                Text = "Complete",
                Value = "1"
            }
        };
    }
}

PlayDeckRazor/Pages/Shared/_DeckDisplay.cshtml
@using PlayDeckRazor.Model
@using Microsoft.AspNetCore.Mvc.TagHelpers
@model IndexModel

@* Displays games associated with the corresponding deck id *@

@{
    if (ViewData["Deck"] is Deck d)
    {
        <div id="@d.Title-container" class="deck-display-container d-flex flex-column justify-content-center" x-data="{ search: '', expanded: true, showHide: 'Hide'}">
            <div id="@d.Title-header" class="deck-header d-flex">
                <div id="@d.Title-title" class="deck-title">
                    <h1>@d.Title</h1>
                </div>
                <div class="add-game-button-container">
                    <a class="add-game-button btn btn-primary" data-bs-toggle="modal" data-bs-target="#delete-modal" x-on:click="ResetGameDetails(); mode = 'add'; deckId = @d.ID; @d.ID == 2 ? playStatus = 1 : playStatus = 0; deckTitle = '@d.Title'" role="button" title="Add new card to deck">+</a>
                </div>
                @{
                    @* If deck is 'My Collection' (Unassigned) include search as could contain many entries *@
                    if (d.ID == 0) 
                    {
                        <div class="deck-search ">
                            <form x-on:submit.prevent="{}">
                                <p>
                                    <input x-on:keyup.enter.prevent="{}" type="text" x-model.debounce="search" placeholder="Search..."/>
                                </p>
                            </form>
                        </div>
                        <div class="hide-button-container" style="margin-left: 0.5vw">
                            <button x-on:click="expanded = ! expanded; expanded ? showHide = 'Hide' : showHide = 'Show'" x-text="showHide" class="btn btn-primary hide-button"></button>
                        </div>
                    }
                    else
                    {
                        <div class="hide-button-container">
                            <button x-on:click="expanded = ! expanded; expanded ? showHide = 'Hide' : showHide = 'Show'" x-text="showHide" class="btn btn-primary hide-button"></button>
                        </div>
                    }
                    <div class="view-all-container">
                        <a class="view-all-button" asp-page="/Decks/View" asp-route-id="@d.ID" asp-route-Title="@d.Title">View All
                            <span class="badge bg-secondary" >@d.GameList.Count</span>
                        </a>
                    </div>
                }
                
            </div>
            <div id="@d.Title-display" class="deck-display d-flex justify-content-center" x-show="expanded">
                <ul id="@d.Title-cards" class="deck d-flex flex-wrap" deckDisplay="@d.ID">
                    @{
                        List<Game> sortedList;
                        switch (d.ID)
                        {
                            case 0:
                                @* 'My Collection', sort by alphabetical, Display 20 cards *@
                                sortedList = d.GameList.OrderBy(g=>g.Title).ToList(); 
                                for (int i = 0; i < 20 && i < sortedList.Count; i++)
                                {
                                    ViewData["GameCard"] = sortedList[i];
                                    await Html.RenderPartialAsync("_GameCard", Model);
                                }
                                break;
                            case 1:
                                 @* 'Currently Playing', sort by least recently started, Display all cards *@
                                sortedList = d.GameList.OrderBy(g=>g.StartDate).ToList();
                                for (int i = 0; i < sortedList.Count; i++)
                                {
                                    ViewData["GameCard"] = sortedList[i];
                                    await Html.RenderPartialAsync("_GameCard", Model);
                                }
                                break;
                            case 2:
                                 @* 'Complete', Sort by most recently completed, Display 5 cards *@
                                sortedList = d.GameList.OrderByDescending(g=>g.CompleteDate).ToList();
                                for (int i = 0; i < 5 && i < sortedList.Count; i++)
                                {
                                    ViewData["GameCard"] = sortedList[i];
                                    await Html.RenderPartialAsync("_GameCard", Model);
                                }
                                break;
                            case 3:
                                 @* 'Wishlist', Sort by most recently added (DB id), Display 5 cards *@
                                sortedList = d.GameList.OrderByDescending(g=>g.ID).ToList();
                                for (int i = 0; i < 5 && i < sortedList.Count; i++)
                                {
                                    ViewData["GameCard"] = sortedList[i];
                                    await Html.RenderPartialAsync("_GameCard", Model);
                                }
                                break;
                            case 4:
                                 @* 'Favourites', Sort by most recently added (DB id), Display 5 cards *@
                                sortedList = d.GameList.OrderByDescending(g=>g.ID).ToList();
                                for (int i = 0; i < 5 && i < sortedList.Count; i++)
                                {
                                    ViewData["GameCard"] = sortedList[i];
                                    await Html.RenderPartialAsync("_GameCard", Model);
                                }
                                break;
                            default:
                                @* Future proofing for display of any custom decks user has made *@
                                foreach (Game g in d.GameList)
                                {
                                    ViewData["GameCard"] = g;
                                    await Html.RenderPartialAsync("_GameCard", Model);
                                }
                                break;
                        }
                    }
                </ul>
            </div>
        </div> 
    }
}

PlayDeckRazor/Pages/Shared/_GameInfoPanel.cshtml
@using PlayDeckRazor.Model
@model GameViewModel

@* Displays details about a game entry *@

@{
    if (ViewData["GameView"] is Game g)
    {
        <div id="info-panel" class="game-info d-flex flex-column">
            <div class="game-info-header d-flex">
                <div style="margin-top: 1vw; margin-right: 1vw">
                    @{
                        if (g.Favourite)
                        {
                            <form id="fav-change-form" method="post" x-on:submit.prevent="toggleFavGameView(@g.ID)" asp-page-handler="togglefavgameview">
                                <input asp-for="GameID" class="form-control" value="@g.ID" type="hidden"/>
                                <input asp-for="ToggleFavourite" class="form-control" value="true" type="hidden"/>
                                <button class="heart-button bi bi-heart-fill heart-checked"
                                        type="submit"
                                        x-on:submit.prevent="{}"
                                        title="Toggle favourite">
                                </button>
                            </form>
                        }
                        else
                        {
                            <form id="fav-change-form" method="post" x-on:submit.prevent="toggleFavGameView(@g.ID)" asp-page-handler="togglefavgameview">
                                <input asp-for="GameID" class="form-control" value="@g.ID" type="hidden"/>
                                <input asp-for="ToggleFavourite" class="form-control" value="true" type="hidden"/>
                                <button class="heart-button bi bi-heart heart-unchecked"
                                        type="submit"
                                        x-on:submit.prevent="{}"
                                        title="Toggle favourite">
                                </button>
                            </form>
                        }
                    }
                </div>
                <h1>@g.Title</h1>


            </div>
            @{
               @* Star Rating Display *@
                if (g.Rating != null)
                {
                    <div class="d-flex" style="gap: 1vw">
                        @{
                            for (int i = 1; i < 11; i++)
                            {
                                if (i <= @g.Rating) @* Filled stars *@
                                {
                                    <form x-data="{formID: @i}" id="star-form-@i" method="post" x-on:submit.prevent="changeRating(formID, @g.ID)" asp-page-handler="ratingchange">
                                        <input asp-for="GameID" class="form-control" value="@g.ID" type="hidden"/>
                                        <input asp-for="RatingChange" class="form-control" value="@i" type="hidden"/>
                                        <button class="star-button bi bi-star-fill checked"
                                                type="submit"
                                                x-on:submit.prevent="{}"
                                                title="@i /10">
                                        </button>
                                    </form>
                                }
                                else @* Empty stars *@
                                {
                                    <form x-data="{formID: @i}" id="star-form-@i" method="post" x-on:submit.prevent="changeRating(formID, @g.ID)" asp-page-handler="ratingchange">
                                        <input asp-for="GameID" class="form-control" value="@g.ID" type="hidden"/>
                                        <input asp-for="RatingChange" class="form-control" value="@i" type="hidden"/>
                                        <button class="star-button bi bi-star unchecked"
                                                type="submit"
                                                x-on:submit.prevent="{}"
                                                title="@i /10">
                                        </button>
                                    </form>
                                }
                    
                            }
                        }
                    </div>
                
                }
                else @* If no rating, display 10 empty stars *@
                {
                    <div class="d-flex" style="gap: 1vw">
                        @{
                            for (int i = 1; i < 11; i++)
                            {
                                <form x-data="{formID: @i}" id="star-form-@i" method="post" x-on:submit.prevent="changeRating(formID, @g.ID)" asp-page-handler="ratingchange">
                                    <input asp-for="GameID" class="form-control" value="@g.ID" type="hidden"/>
                                    <input asp-for="RatingChange" class="form-control" value="@i" type="hidden"/>
                                    <button class="star-button bi bi-star unchecked"
                                            type="submit"
                                            x-on:submit.prevent="{}"
                                            title="@i /10">
                                    </button>
                                </form>
                            } 
                        }
                    </div>
                }
               
               @* Game Details Display *@
                <div class="d-flex" style="gap: 1vw; margin-top: 2vw">
                    <div class="d-flex flex-column" style="gap: 2vw; width: 17vw;">
                        <div class="d-flex" style="gap: 1vw;">
                            @{
                                if (g.PlayStatus == 1) @* Game has been completed *@
                                {
                                    <form id="playstatus-form" method="post" x-on:submit.prevent="changePlayStatus(@g.ID)" asp-page-handler="changeplaystatus">
                                        <input asp-for="GameID" class="form-control" value="@g.ID" type="hidden"/>
                                        <input asp-for="PlayStatusChange" class="form-control" value="0" type="hidden"/>
                                        <button class="trophy-button bi-trophy-fill trophy-checked"
                                                type="submit"
                                                x-on:submit.prevent="{}"
                                                title="Toggle complete status">
                                        </button>
                                    </form>
                                    <h2 class="play-status-text">Complete</h2>
                                }
                                else
                                {
                                    <form id="playstatus-form" method="post" x-on:submit.prevent="changePlayStatus(@g.ID)" asp-page-handler="changeplaystatus">
                                        <input asp-for="GameID" class="form-control" value="@g.ID" type="hidden"/>
                                        <input asp-for="PlayStatusChange" class="form-control" value="1" type="hidden"/>
                                        <button class="trophy-button bi-trophy trophy-unchecked"
                                                type="submit"
                                                x-on:submit.prevent="{}"
                                                title="Toggle complete status">
                                        </button>
                                    </form>
                                    <h2 class="play-status-text">Unfinished</h2>
                                }
                            }
                        </div>
                       
                        @{
                            if (g.PlayTime > 0)
                            {
                                <h3>Play time: @(g.PlayTime)h</h3>
                            }
                            else
                            {
                                <h3>Play time: None</h3>
                            }
                        }

                        @{
                            if (g.LastPlayed != null)
                            {
                                <h3>Last Played: @g.LastPlayed?.ToShortDateString()</h3>
                            }
                            else
                            {
                                <h3>Last Played: Never</h3>
                            }
                        }
                       
                       
                        <a class="edit-details-button btn" data-bs-toggle="modal" data-bs-target="#delete-modal" title="Edit game details" x-on:click="GetGameDetails(@g.ID); mode = 'edit'">Edit Details</a>
                    </div>
                   
                               
                    <div class="d-flex flex-column" style="gap: 2vw;">
                        <div class="d-flex">
                            @{
                                string s = "None";
                                switch (g.DeckID)
                                {
                                    case 0:
                                        s = "My Collection";
                                        break;
                                    case 1:
                                        s = "Currently Playing";
                                        break;
                                    case 2:
                                        s = "Complete";
                                        break;
                                    case 3:
                                        s = "Wishlist";
                                        break;
                                }
                                <h3 style="margin-top: 8px">Deck: @s</h3>
                                <h3 class="deck-link-container" title="View all cards in deck"><a id="deck-link" class="deck-link bi bi-arrow-right-square-fill" href="/Decks/View/@g.DeckID/@s"></a></h3>
                               
                            }
                        </div>
                       
                        @{
                            if (g.StartDate != null)
                            {
                                <h3>Start Date: @g.StartDate?.ToShortDateString()</h3>
                            }
                            else
                            {
                                <h3>Start Date: Unknown</h3>
                            }
                        }
                        @{
                            if (g.PlayStatus == 1 && g.CompleteDate != null)
                            {
                                <h3>Complete Date: @g.CompleteDate?.ToShortDateString()</h3>
                            }
                            else if (g.PlayStatus == 1 && g.CompleteDate == null)
                            {
                                <h3>Complete Date: Unknown</h3>
                            }
                        }
                       
                        <button class="delete-button btn" type="button" data-bs-toggle="modal" data-bs-target="#delete-modal" title="Delete game" x-on:click="setInfo(@g.ID, `@g.Title`); mode = 'delete'">Delete</button>
                    </div>
                </div>
            }

        </div> 
    }
    
}