PlayDeckRazor/Pages/Error.cshtml.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace PlayDeckRazor.Pages;

[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
[IgnoreAntiforgeryToken]
public class ErrorModel : PageModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

    private readonly ILogger<ErrorModel> _logger;

    public ErrorModel(ILogger<ErrorModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {
        RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
    }
}

PlayDeckRazor/Pages/GameView.cshtml.cs
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PlayDeckRazor.Data;
using PlayDeckRazor.Model;

namespace PlayDeckRazor.Pages;

public class GameViewModel : PageModel
{
    
    public readonly PlayDeckRazorContext _context;
    
    
    public Game? Game { get; set; }
    
    [BindProperty]
    public int? RatingChange { get; set; }
    [BindProperty]
    public int? PlayStatusChange { get; set; }
    [BindProperty]
    public int GameID { get; set; }
    
    [BindProperty]
    public int? GameDeleteID { get; set; }
    
    public bool ToggleFavourite { get; set; }
    
    [StringLength(50, MinimumLength = 1), Display(Name = "Title")]
    [BindProperty]
    public string? TitleChange { get; set; }
    
    public GameViewModel(PlayDeckRazorContext context)
    {
        _context = context;
    }
    
    public async Task<IActionResult> OnGetAsync(int id)
    {
        Game = await _context.Game.FindAsync(id);
        if (Game == null)
        {
            return NotFound();
        }
        return Page();
    }

    public async Task<IActionResult> OnPostAsync()
    {
        
        if (!ModelState.IsValid)
        {
            return Page();
        }

        if (GameDeleteID != null)
        {
            // Ensure game exists and delete
            Game = await _context.Game.FindAsync(GameDeleteID);
            if (Game == null)
            {
                return NotFound();
            }
            _context.Remove(Game);
            await _context.SaveChangesAsync();
            return RedirectToPage("/Index");
        }
        
        Game = await _context.Game.FindAsync(GameID);
        if (Game == null)
        {
            return NotFound();
        }
        
        if (RatingChange != null)
        {
            Game.Rating = RatingChange;
        }

        if (PlayStatusChange != null)
        {
            Game.PlayStatus = PlayStatusChange;
        }
        
        if (TitleChange != null)
        {
            Game.Title = TitleChange;
        }
        
        _context.Attach(Game).State = EntityState.Modified;
        
        await _context.SaveChangesAsync();

        return Page();
    }
}

PlayDeckRazor/Pages/Games/Gateway.cshtml.cs
using System.Collections;
using System.Text;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.ViewFeatures;
using Microsoft.EntityFrameworkCore;
using NuGet.Protocol;
using PlayDeckRazor.Data;
using PlayDeckRazor.Model;
using System;
using System.IO;
using System.Text;

namespace PlayDeckRazor.Pages.Games;

public class GatewayModel : PageModel
{
    private readonly PlayDeckRazor.Data.PlayDeckRazorContext _context;
    
    [BindProperty(SupportsGet = true)]
    public Game Game { get; set; } = default!;
    
    [BindProperty(SupportsGet = true)]
    public int? DeckID { get; set; }
    
    /// <summary>
    /// 0 = Unplayed, 1 = Complete
    /// </summary>
    [BindProperty]
    public int? PlayStatusChange { get; set; }
    [BindProperty]
    public int? RatingChange { get; set; }
    [BindProperty]
    public int? GameID { get; set; }
    
    [BindProperty]
    public bool ToggleFavourite { get; set; }
    
    [BindProperty]
    public string Fav_Toggle { get; set; }

    /// <summary>
    /// id for game to be deleted, submitted by post from _GameCard delete button
    /// </summary>
    [BindProperty]
    public int? GameDeleteId { get; set; }
    
    public GatewayModel(PlayDeckRazorContext context)
    {
        _context = context;
    }
    
    /// <summary>
    /// Takes an ID of a game and returns all details of that game as JSON
    /// </summary>
    /// <param name="id">ID of Game in database</param>
    /// <returns></returns>
    public async Task<IActionResult> OnGetRetrieveAsync(int? id)
    {
        if (_context.Game == null)
        {
            return new NotFoundResult();
        }
        
        var game =  await _context.Game.FirstOrDefaultAsync(g => g.ID == id);
        if (game == null)
        {
            return new NotFoundResult();
        }
        Game = game;
        return new OkObjectResult(game.ToJson());
    }

    /// <summary>
    /// Saves all changes of the posted game if it exists in the database
    /// Returns HTML of a new Game Card with updated details.
    /// </summary>
    /// <returns>_GameCard HTML</returns>
    public async Task<IActionResult> OnPostEditAsync()
    {
        if (!ModelState.IsValid)
        {
            return new BadRequestResult();
        }

        if (GameExists(Game.ID))
        {
            if (Fav_Toggle.Equals("Favourite"))
            {
                Game.Favourite = true;
            }
            _context.Attach(Game).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!GameExists(Game.ID))
                {
                    return new NotFoundResult();
                }
                else
                {
                    throw;
                }
            }
            IndexModel newPartialModel = new IndexModel(_context);
            ViewDataDictionary newViewData = new ViewDataDictionary(new Microsoft.AspNetCore.Mvc.ModelBinding.EmptyModelMetadataProvider(),
                new Microsoft.AspNetCore.Mvc.ModelBinding.ModelStateDictionary()) { { "IndexModel", newPartialModel } };
            newViewData.Model = newPartialModel;
            newViewData["GameCard"] = Game;
            return new PartialViewResult()
            {
                ViewName = "_GameCard",
                ViewData = newViewData,
            };
        }
        return new BadRequestResult();
    }
    
    /// <summary>
    /// Saves all changes of the posted game if it exists in the database
    /// Returns HTML of a new Game Info Panel with updated details.
    /// </summary>
    /// <returns>_GameInfoPanel HTML</returns>
    public async Task<IActionResult> OnPostEditGameViewAsync()
    {
        if (!ModelState.IsValid)
        {
            return new BadRequestResult();
        }

        if (GameExists(Game.ID))
        {
            if (Fav_Toggle.Equals("Favourite"))
            {
                Game.Favourite = true;
            }
            _context.Attach(Game).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!GameExists(Game.ID))
                {
                    return new NotFoundResult();
                }
                else
                {
                    throw;
                }
            }
            GameViewModel newPartialModel = new GameViewModel(_context);
            ViewDataDictionary newViewData = new ViewDataDictionary(new Microsoft.AspNetCore.Mvc.ModelBinding.EmptyModelMetadataProvider(),
                new Microsoft.AspNetCore.Mvc.ModelBinding.ModelStateDictionary()) { { "GameViewModel", newPartialModel } };
            newViewData.Model = newPartialModel;
            newViewData["GameView"] = Game;
            return new PartialViewResult()
            {
                ViewName = "_GameInfoPanel",
                ViewData = newViewData,
            };
        }
        return new BadRequestResult();
    }

    /// <summary>
    /// Adds posted game to the database
    /// Returns HTML of new Game Card
    /// </summary>
    /// <returns>_GameCard HTML</returns>
    public async Task<IActionResult> OnPostAddAsync()
    {
        if (ModelState.IsValid && !GameExists(Game.ID))
        {
            if (Fav_Toggle.Equals("Favourite"))
            {
                Game.Favourite = true;
            }
            _context.Game.Add(Game);
            await _context.SaveChangesAsync();

            IndexModel newPartialModel = new IndexModel(_context);
            ViewDataDictionary newViewData = new ViewDataDictionary(new Microsoft.AspNetCore.Mvc.ModelBinding.EmptyModelMetadataProvider(),
                new Microsoft.AspNetCore.Mvc.ModelBinding.ModelStateDictionary()) { { "IndexModel", newPartialModel } };
            newViewData.Model = newPartialModel;
            newViewData["GameCard"] = Game;
            return new PartialViewResult()
            {
                ViewName = "_GameCard",
                ViewData = newViewData,
            };
        }
        else
        {
            return new BadRequestResult();
        }
        
    }

    private bool GameExists(int id)
    {
        return (_context.Game?.Any(e => e.ID == id)).GetValueOrDefault();
    }
    
    /// <summary>
    /// Finds game with posted ID and removes it from the database
    /// </summary>
    /// <returns>Posted Game ID</returns>
    public async Task<IActionResult> OnPostDeleteAsync()
    {
        
        if (GameDeleteId != null)
        {
            // Ensure game exists and delete
            var game = await _context.Game.FindAsync(GameDeleteId);
            if (game != null)
            {
                _context.Remove(game);
                await _context.SaveChangesAsync();
                return new OkObjectResult(GameDeleteId);
            }
            
            return new NotFoundResult();
            
        }
        return new BadRequestResult();
    }

    /// <summary>
    /// Finds game by posted Game ID and updates its rating property
    /// Returns HTML of new Game Info Panel
    /// </summary>
    /// <returns>_GameInfoPanel HTML</returns>
    public async Task<IActionResult> OnPostRatingChangeAsync()
    {
        Game = await _context.Game.FindAsync(GameID);
        if (Game == null)
        {
            return new NotFoundResult();
        }
        
        if (RatingChange != null)
        {
            Game.Rating = RatingChange;
        } 
        else
        {
            return new BadRequestResult();
        }
        
        _context.Attach(Game).State = EntityState.Modified;
        
        await _context.SaveChangesAsync();

        GameViewModel newPartialModel = new GameViewModel(_context);
        ViewDataDictionary newViewData = new ViewDataDictionary(new Microsoft.AspNetCore.Mvc.ModelBinding.EmptyModelMetadataProvider(),
            new Microsoft.AspNetCore.Mvc.ModelBinding.ModelStateDictionary()) { { "GameViewModel", newPartialModel } };
        newViewData.Model = newPartialModel;
        newViewData["GameView"] = Game;
        return new PartialViewResult()
        {
            ViewName = "_GameInfoPanel",
            ViewData = newViewData,
        };
    }

    /// <summary>
    /// Finds game by posted Game ID and updates its PlayStatus property
    /// Returns new Game Info Panel HTML
    /// </summary>
    /// <returns>_GameInfoPanel HTML</returns>
    public async Task<IActionResult> OnPostPlayStatusChangeAsync()
    {
        Game = await _context.Game.FindAsync(GameID);
        if (Game == null)
        {
            return new NotFoundResult();
        }
        
        if (PlayStatusChange != null)
        {
            Game.PlayStatus = PlayStatusChange;
        }
        else
        {
            return new BadRequestResult();
        }
        
        _context.Attach(Game).State = EntityState.Modified;
        
        await _context.SaveChangesAsync();

        GameViewModel newPartialModel = new GameViewModel(_context);
        ViewDataDictionary newViewData = new ViewDataDictionary(new Microsoft.AspNetCore.Mvc.ModelBinding.EmptyModelMetadataProvider(),
            new Microsoft.AspNetCore.Mvc.ModelBinding.ModelStateDictionary()) { { "GameViewModel", newPartialModel } };
        newViewData.Model = newPartialModel;
        newViewData["GameView"] = Game;
        return new PartialViewResult()
        {
            ViewName = "_GameInfoPanel",
            ViewData = newViewData,
        };
    }
    
    /// <summary>
    /// Finds game by posted Game ID and updates its Favourite property
    /// Returns new Game Info Panel HTML
    /// </summary>
    /// <returns>_GameInfoPanel HTML</returns>

PlayDeckRazor/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using PlayDeckRazor.Data;
using PlayDeckRazor.Model;

namespace PlayDeckRazor.Pages;

public class IndexModel : PageModel
{
    public readonly PlayDeckRazorContext _context;

    /// <summary>
    /// List of Decks containing all Games in the DB, Max 10 decks, 0 = Unassigned, 1 = Currently Playing, 2 = completed,
    /// 3 = Wishlist, 4 = Favourites
    /// 5 -> 10 for user allocation
    /// </summary>
    public List<Deck> Decks = new List<Deck>(10);

    public List<Game>? FilteredList { get; set; }
    
    public int? GameID { get; set; }
    public bool ToggleFavourite { get; set; }
    
    [BindProperty]
    public int? GameDeleteId { get; set; }
    
    /* Not Implemented yet
    public SelectList? Platform { get; set; }
    [BindProperty(SupportsGet = true)]
    public string? PlatformSearch { get; set; }
    */

    public IndexModel(PlayDeckRazorContext context)
    {
        _context = context;
        
        // TODO: Replace with db query when Deck storage is implemented
        for (int i = 0; i < Decks.Capacity; i++)
        {
            Decks.Add(new Deck(i));
        }
        Decks[0].Title = "My Collection";
        Decks[1].Title = "Currently Playing";
        Decks[2].Title = "Complete";
        Decks[3].Title = "Wishlist";
        Decks[4].Title = "Favourites";
    }

    public async Task OnGetAsync()
    {
        // Add each game to respective deck
        await foreach (Game g in _context.Game)
        {
            Decks[g.DeckID].GameList.Add(g);
            // Games tagged as favourites exist in other decks, i.e. their DeckID does not determine if they
            // should appear in the favourites deck
            if (g.Favourite)
            {
                Decks[4].GameList.Add(g);
            }
        }
    }
    
}

PlayDeckRazor/Pages/GameView.cshtml
@page "{id:int}"
@using PlayDeckRazor.Pages.Shared
@model PlayDeckRazor.Pages.GameViewModel

@{
    ViewData["Title"] = Model.Game?.Title + " Details";
}

@* Page for displaying single game details *@

<div x-data="$store.gameData">
    <div class="modal fade" id="delete-modal" tabindex="-1" role="dialog" aria-labelledby="delete-modal-title" aria-hidden="true">
        <div class="modal-dialog modal-xl modal-dialog-centered" role="document">
            <div class="modal-content" x-on:click="addValidation()">
                <div class="modal-header">
                    <template x-if="mode === 'delete'">
                        <h2 class="modal-title" id="delete-modal-title">Warning!</h2>
                    </template>
                    <template x-if="mode === 'edit'">
                        <h2 class="modal-title" id="delete-modal-title">Edit: <span x-text="gameTitle"></span></h2>
                    </template>
                </div>
                <div class="modal-body">
                    <template x-if="mode === 'delete'">
                        <p>
                            Are you sure you want to remove <span style="color: #eb4155; font-weight: bold" x-text="gameTitle"></span> from your collection? If you want to change which deck
                            the game belongs to, use the edit button.
                        </p>
                    </template>
                    <template x-if="mode === 'edit'">
                        @{
                            await Html.RenderPartialAsync("_ModalGameDetails", new _ModalGameDetailsModel(Model._context));
                        }
                    </template>
                    <template x-if="mode === 'add'">
                        @{
                            await Html.RenderPartialAsync("_ModalGameDetails", new _ModalGameDetailsModel(Model._context));
                        }
                    </template>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal" title="Cancel">Cancel</button>
                    <template x-if="mode === 'delete'">
                        <form x-on:submit.prevent="SendDelete(true)" method="post" id="delete-modal-form" asp-page-handler="delete">
                            <input type="hidden" asp-for="@Model.GameDeleteID" x-model="gameId"/>
                            <input x-on:submit.prevent="{}" type="submit" value="I'm Sure" class="btn btn-danger" title="Delete game" data-bs-toggle="modal" data-bs-target="#delete-modal"/>
                        </form>
                    </template>
                    <template x-if="mode === 'edit'">
                        <form x-on:submit.prevent="checkValid($refs.editSubmit) ? SendEditGameView(gameId) : {}" method="post" id="edit-modal-button-form" asp-page-handler="editgameview">
                            <input x-ref="editSubmit" x-on:submit.prevent="{}" type="submit" value="Save" class="btn btn-primary submit-button" style="margin-left: auto" title="Save changes"/>
                        </form>
                    </template>
                </div>
            </div>
        </div>
    </div>
    
    <div class="d-flex" id="page-container" style="margin-top: 4vw">
        <div x-data="{altText: ''}" class="game-cover-container">
            @{
                
                
                <template x-if="imageUrl || `@Model.Game?.ImageURL`">
                    <img class="game-cover-image" x-bind:src="imageUrl ? imageUrl : `@Model.Game?.ImageURL`" x-bind:alt="gameTitle ? gameTitle  + ' video-game cover' : `@Model.Game?.Title` + ' video-game cover'">
                </template>
                <template x-if="!imageUrl && !`@Model.Game?.ImageURL`">
                    <div class="placeholder-container">
                        <img class="game-cover-image" src="/Resources/Cover Placeholder.png" x-bind:alt="gameTitle ? gameTitle  + ' video-game cover' : `@Model.Game?.Title` + ' video-game cover'">
                        <p class="placeholder-text" x-text="gameTitle ? gameTitle : `@Model.Game?.Title`"></p>
                    </div>
                </template>
            }
        </div>
        <div id="game-info-container" class="game-info-container">
            @{ ViewData["GameView"] = Model.Game;}
            @{await Html.RenderPartialAsync("_GameInfoPanel");}
        </div>
    </div>
    
    <div class="toast-container position-fixed bottom-0 end-0 p-3" style="z-index: 1">
        <div id="liveToast" class="toast bg-dark bg-gradient" role="alert" aria-live="assertive" aria-atomic="true">
            <div class="toast-header bg-transparent text-white">
                <img src="/favicon.ico" class="rounded me-2" alt="...">
                <strong class="me-auto" id="toast-operation">Deleted</strong>
                <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
            </div>
            <div class="toast-body bg-transparent text-white">
                <span style="color: #eb4155; font-weight: bold" x-text="gameTitle"></span> <span id="toast-operation-text">was removed from the database.</span>
            </div>
        </div>
    </div>
</div>

<script src="~/js/gameview.js" asp-append-version="true"></script>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

PlayDeckRazor/Pages/Index.cshtml
@page
@using PlayDeckRazor.Pages.Shared
@using PlayDeckRazor.Model
@using Microsoft.AspNetCore.Mvc.TagHelpers
@model IndexModel
@{
    ViewData["Title"] = "Home";
}

<div x-data="$store.gameData">
    <div class="modal fade" id="delete-modal" tabindex="-1" role="dialog" aria-labelledby="delete-modal-title" aria-hidden="true">
        <div class="modal-dialog modal-xl modal-dialog-centered" role="document">
            <div class="modal-content" x-on:click="addValidation()">
                <div class="modal-header">
                    <template x-if="mode === 'delete'">
                        <h2 class="modal-title" id="delete-modal-title">Warning!</h2>
                    </template>
                    <template x-if="mode === 'edit'">
                        <h2 class="modal-title" id="delete-modal-title">Edit: <span x-text="gameTitle"></span></h2>
                    </template>
                    <template x-if="mode === 'add'">
                        <h2 class="modal-title" id="delete-modal-title">Add a New Game</h2>
                    </template>
                    <template x-if="mode === 'import'">
                        <h2 class="modal-title" id="delete-modal-title">Import Game Data</h2>
                    </template>
                    <template x-if="mode === 'export'">
                        <h2 class="modal-title" id="delete-modal-title">Export Game Data</h2>
                    </template>
                </div>
                <div class="modal-body">
                    <template x-if="mode === 'delete'">
                        <p>
                            Are you sure you want to remove <span style="color: #eb4155; font-weight: bold" x-text="gameTitle"></span> from your collection? If you want to change which deck
                            the game belongs to, use the edit button.
                        </p>
                    </template>
                    <template x-if="mode === 'edit'">
                        @{
                            await Html.RenderPartialAsync("_ModalGameDetails", new _ModalGameDetailsModel(Model._context));
                        }
                    </template>
                    <template x-if="mode === 'add'">
                        @{
                            await Html.RenderPartialAsync("_ModalGameDetails", new _ModalGameDetailsModel(Model._context));
                        }
                    </template>
                    <template x-if="mode === 'import'">
                        <p>
                            Are you sure you want to import your game data? This will not check for duplicates 
                            and will add all the games from the file as if they are new entries
                        </p>
                    </template>
                    <template x-if="mode === 'export'">
                        <p>
                            Are you sure you want to export your game data? This will overwrite any previously exported data.
                        </p>
                    </template>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal" title="Cancel">Cancel</button>
                    <template x-if="mode === 'delete'">
                        <form x-on:submit.prevent="SendDelete()" method="post" id="delete-modal-form" asp-page-handler="delete">
                            <input type="hidden" asp-for="GameDeleteId" x-model="gameId"/>
                            <input x-on:submit.prevent="{}" type="submit" value="I'm Sure" class="btn btn-danger" title="Delete game" data-bs-toggle="modal" data-bs-target="#delete-modal"/>
                        </form>
                    </template>
                    <template x-if="mode === 'edit'">
                        <form x-on:submit.prevent="checkValid($refs.editSubmit) ? SendEdit(gameId) : {}" method="post" id="edit-modal-button-form" asp-page-handler="edit">
                            <input x-ref="editSubmit" x-on:submit.prevent="{}" type="submit" value="Save" class="btn btn-primary submit-button" style="margin-left: auto" title="Save changes"/>
                        </form>
                    </template>
                    <template x-if="mode === 'add'">
                        <form x-on:submit.prevent="checkValid($refs.addSubmit) ? SendAdd(deckTitle) : {}" method="post" id="add-modal-button-form" asp-page-handler="add">
                            <input x-ref="addSubmit" x-on:submit.prevent="{}" type="submit" value="Create" class="btn btn-primary submit-button" title="Add new game" />
                        </form>
                    </template>
                    <template x-if="mode === 'import'">
                        <form x-data id="import-form" method="post" x-on:submit.prevent="importGames()" asp-page-handler="import">
                            <button class="import-button"
                                    type="submit"
                                    x-on:submit.prevent="{}"
                                    title="Import">Import
                            </button>
                        </form>
                    </template>
                    <template x-if="mode === 'export'">
                        <form x-data id="export-form" method="post" x-on:submit.prevent="exportGames()" asp-page-handler="export" >
                            <button class="export-button"
                                    type="submit"
                                    x-on:submit.prevent="{}"
                                    data-bs-dismiss="modal"
                                    title="Export">Export
                            </button>
                        </form>
                    </template>
                </div>
            </div>
        </div>
    </div>
    
    @* These decks will always be displayed first *@
    <div id="default-decks-container" class="d-flex flex-column justify-content-center">
        @{
            @* Deck ID 1 = Currently Playing (On Deck) *@
            ViewData["Deck"] = Model.Decks[1];
            await Html.RenderPartialAsync("_DeckDisplay", Model);
        }
        @{
            @* Deck ID 2 = Complete *@
            ViewData["Deck"] = Model.Decks[2];
            await Html.RenderPartialAsync("_DeckDisplay", Model);
        }
        @{
            @* Deck ID 3 = Wishlist *@
            ViewData["Deck"] = Model.Decks[3];
            await Html.RenderPartialAsync("_DeckDisplay", Model);
        }
        @{  
            @* Deck ID 4 = Favourites *@
            ViewData["Deck"] = Model.Decks[4];
            await Html.RenderPartialAsync("_DeckDisplay", Model);
        }
    </div>
    
    @* Space for custom decks *@
    
    @{
        @* Deck ID 0 = Collection / Unassigned *@
        ViewData["Deck"] = Model.Decks[0];
        await Html.RenderPartialAsync("_DeckDisplay", Model);
    }
    
    <div class="toast-container position-fixed bottom-0 end-0 p-3" style="z-index: 1">
        <div id="liveToast" class="toast bg-dark bg-gradient" role="alert" aria-live="assertive" aria-atomic="true">
            <div class="toast-header bg-transparent text-white">
                <img src="favicon.ico" class="rounded me-2" alt="...">
                <strong class="me-auto" id="toast-operation">Deleted</strong>
                <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
            </div>
            <div class="toast-body bg-transparent text-white">
                <span style="color: #eb4155; font-weight: bold" x-text="gameTitle"></span> <span id="toast-operation-text">was removed from the database.</span>
            </div>
        </div>
    </div>
    
    <div class="d-flex gap-2">
        <div class="ms-auto">
            <button class="export-button"
                    type="submit"
                    x-on:submit.prevent="{}"
                    data-bs-toggle="modal" data-bs-target="#delete-modal"
                    x-on:click="mode = 'export'"
                    title="Export">Export
            </button>
        </div>
        <div class="me-auto">
            <button class="import-button"
                    type="submit"
                    x-on:submit.prevent="{}"
                    title="Import"
                    data-bs-toggle="modal" data-bs-target="#delete-modal"
                    x-on:click="mode = 'import'"
            >Import
            </button>
        </div>
    </div>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}